"""Generate complete, runnable inference scripts for any hardware + model.

Each generated script is:
  - Self-contained (no external dependencies beyond ORT + numpy)
  - Correctly configured for the detected hardware
  - Has environment variable setup baked in
  - Has swap / kernel param checks
  - Has a professional header with copyright and hardware fingerprint
  - Actually runs end-to-end (tested on real hardware)
"""

from __future__ import annotations

import hashlib
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from isat import __version__
from isat.auto_detect.detector import DetectedGPU, HardwareProfile


def _fingerprint(hw: HardwareProfile, model_path: str) -> str:
    """Generate a unique hash for this hardware + model combination."""
    gpu = hw.primary_gpu
    identity = (
        f"{hw.cpu_name}:{hw.system_ram_mb}:"
        f"{gpu.vendor if gpu else 'cpu'}:{gpu.arch if gpu else ''}:"
        f"{gpu.vram_mb if gpu else 0}:{gpu.shared_mem_mb if gpu else 0}:"
        f"{model_path}"
    )
    return hashlib.sha256(identity.encode()).hexdigest()[:12]


def _model_basename(model_path: str) -> str:
    return Path(model_path).stem.replace("-", "_").replace(".", "_")


# ---------------------------------------------------------------------------
# AMD APU Script
# ---------------------------------------------------------------------------

def _amd_apu_script(hw: HardwareProfile, gpu: DetectedGPU,
                    model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    runtime_gb = model_mb * 2.5 / 1024
    need_swap_warning = runtime_gb > 8
    need_template_depth = model_mb > 500
    swap_recommended = max(int(runtime_gb * 4), 16)

    env_block = f"""\
os.environ["HSA_XNACK"] = "1"
os.environ["MIGRAPHX_GPU_COMPILE_PARALLEL"] = "1"
"""
    if need_template_depth:
        env_block += 'os.environ["MIGRAPHX_GPU_HIP_FLAGS"] = "-ftemplate-depth=2048 -Wno-error=stack-exhausted"\n'

    swap_check = ""
    if need_swap_warning:
        swap_check = f"""
    swap_gb = _get_swap_gb()
    if swap_gb < {swap_recommended}:
        print(f"  [WARNING] Swap is only {{swap_gb:.0f}} GB. Recommended: >= {swap_recommended} GB")
        print(f"  MIGraphX compilation of large models uses heavy swap.")
        print(f"  To add swap:")
        print(f"    sudo fallocate -l {swap_recommended}G /swapfile_isat")
        print(f"    sudo chmod 600 /swapfile_isat")
        print(f"    sudo mkswap /swapfile_isat && sudo swapon /swapfile_isat")
    else:
        print(f"  [OK] Swap: {{swap_gb:.0f}} GB (>= {swap_recommended} GB)")
"""

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, {gpu.gpu_type.upper()})

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  This script is ready to run. It will:
    1. Verify system requirements (GPU, drivers, memory, swap)
    2. Set the correct environment variables for {gpu.arch}
    3. Load and compile the model with MIGraphX EP (FP16)
    4. Run a test inference and print timing
    5. Verify the correct execution provider is active

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-migraphx numpy
"""

import os
import sys
import time
from pathlib import Path

# ============================================================================
#  ENVIRONMENT CONFIGURATION
#  These MUST be set BEFORE importing onnxruntime.
# ============================================================================

{env_block}

# ============================================================================
#  SYSTEM CHECKS
# ============================================================================

def _get_swap_gb() -> float:
    try:
        for line in Path("/proc/meminfo").read_text().splitlines():
            if line.startswith("SwapTotal:"):
                return int(line.split()[1]) / (1024 * 1024)
    except OSError:
        pass
    return 0.0


def _get_vram_mb() -> int:
    for card in sorted(Path("/sys/class/drm").glob("card*/device")):
        vt = card / "mem_info_vram_total"
        if vt.exists():
            try:
                return int(vt.read_text().strip()) // (1024 * 1024)
            except (OSError, ValueError):
                pass
    return 0


def _get_gtt_mb() -> int:
    for card in sorted(Path("/sys/class/drm").glob("card*/device")):
        gt = card / "mem_info_gtt_total"
        if gt.exists():
            try:
                return int(gt.read_text().strip()) // (1024 * 1024)
            except (OSError, ValueError):
                pass
    return 0


def preflight_checks():
    """Verify this system meets all requirements before running."""
    print()
    print("=" * 60)
    print("  ISAT Pre-flight System Check")
    print("=" * 60)
    print()

    ok = True

    # Check HSA_XNACK
    xnack = os.environ.get("HSA_XNACK", "0")
    if xnack == "1":
        print("  [OK] HSA_XNACK=1 (unified memory enabled)")
    else:
        print("  [FAIL] HSA_XNACK not set! Large models will fail.")
        ok = False

    # Check GPU
    vram = _get_vram_mb()
    gtt = _get_gtt_mb()
    if vram > 0 or gtt > 0:
        print(f"  [OK] GPU detected: VRAM={{vram}}MB, GTT={{gtt}}MB")
        if vram < 2048 and gtt > 4096:
            print(f"  [OK] APU mode: unified memory via GTT")
    else:
        print("  [FAIL] No AMD GPU detected in sysfs")
        ok = False
{swap_check}
    # Check ORT
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "MIGraphXExecutionProvider" in providers:
            print("  [OK] MIGraphX EP available")
        else:
            print("  [WARNING] MIGraphX EP not found — will fall back to CPU")
            print("  Install: pip install onnxruntime-migraphx")
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        print("  Install: pip install onnxruntime-migraphx")
        ok = False

    # Check model file
    model = Path(MODEL_PATH)
    if model.exists():
        size_mb = model.stat().st_size / (1024 * 1024)
        print(f"  [OK] Model found: {{size_mb:.1f}} MB")
    else:
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False

    print()
    if ok:
        print("  All checks passed. Ready to run.")
    else:
        print("  Some checks failed. Fix the issues above before running.")
    print("=" * 60)
    print()
    return ok


# ============================================================================
#  MODEL CONFIGURATION
# ============================================================================

MODEL_PATH = r"{model_path}"


# ============================================================================
#  INFERENCE
# ============================================================================

def create_session():
    """Create an ORT inference session with MIGraphX EP."""
    import onnxruntime as ort

    sess_opts = ort.SessionOptions()
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL

    providers = [
        ("MIGraphXExecutionProvider", {{
            "migraphx_fp16_enable": "1",
            "device_id": "0",
        }}),
        "CPUExecutionProvider",
    ]

    print("Loading model and compiling with MIGraphX...")
    print("(First run compiles the model — this can take minutes for large models)")
    print()

    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    compile_time = time.perf_counter() - t0

    # CRITICAL: Verify MIGraphX is actually active
    active_ep = session.get_providers()[0]
    if "MIGraphX" not in active_ep:
        print(f"  [WARNING] Expected MIGraphX but got: {{active_ep}}")
        print(f"  ORT silently fell back to CPU. Check your ORT build.")
    else:
        print(f"  [OK] Running on: {{active_ep}}")

    print(f"  Compile time: {{compile_time:.1f}}s")
    print()
    return session


def run_inference(session, warmup: int = 3, measured: int = 10):
    """Run warmup + measured inference and print timing stats."""
    import numpy as np

    inputs = {{}}
    for inp in session.get_inputs():
        shape = []
        for dim in inp.shape:
            if isinstance(dim, int) and dim > 0:
                shape.append(dim)
            else:
                shape.append(1)

        dtype_map = {{
            "tensor(float)": np.float32,
            "tensor(float16)": np.float16,
            "tensor(int64)": np.int64,
            "tensor(int32)": np.int32,
            "tensor(bool)": np.bool_,
            "tensor(uint8)": np.uint8,
            "tensor(double)": np.float64,
        }}
        np_dtype = dtype_map.get(inp.type, np.float32)
        inputs[inp.name] = np.random.randn(*shape).astype(np_dtype)

    output_names = [o.name for o in session.get_outputs()]

    # Warmup
    print(f"Warmup ({{warmup}} iterations)...")
    for i in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()

    # Measured
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")

    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    mn = min(latencies)
    mx = max(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    fps = 1000.0 / avg if avg > 0 else 0

    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{mn:>10.2f}} ms")
    print(f"  Max    : {{mx:>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{fps:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : MIGraphXExecutionProvider (FP16)")
    print(f"  Target : {gpu.name} ({gpu.arch})")
    print("=" * 60)
    print()


# ============================================================================
#  MAIN
# ============================================================================

if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} ({gpu.arch})")
    print("=" * 60)

    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)

    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# AMD dGPU Script
# ---------------------------------------------------------------------------

def _amd_dgpu_script(hw: HardwareProfile, gpu: DetectedGPU,
                     model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, dGPU, {gpu.vram_mb}MB VRAM)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-migraphx numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

os.environ["HSA_XNACK"] = "0"

MODEL_PATH = r"{model_path}"


def main():
    import onnxruntime as ort

    print()
    print("=" * 60)
    print("  ISAT Inference — AMD dGPU")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  GPU  : {gpu.name} ({gpu.arch}, {gpu.vram_mb}MB VRAM)")
    print("=" * 60)
    print()

    sess_opts = ort.SessionOptions()
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL

    providers = [
        ("MIGraphXExecutionProvider", {{
            "migraphx_fp16_enable": "1",
            "device_id": "0",
        }}),
        "CPUExecutionProvider",
    ]

    print("Loading and compiling model...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    print(f"Compiled in {{time.perf_counter() - t0:.1f}}s")
    print(f"Active EP: {{session.get_providers()[0]}}")
    print()

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))

    output_names = [o.name for o in session.get_outputs()]

    for i in range(3):
        session.run(output_names, inputs)
    print("Warmup done. Benchmarking...")

    latencies = []
    for i in range(10):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        ms = (time.perf_counter() - t0) * 1000
        latencies.append(ms)
        print(f"  Run {{i+1:>2}}: {{ms:.2f}} ms")

    avg = sum(latencies) / len(latencies)
    print(f"\\nMean: {{avg:.2f}} ms | FPS: {{1000/avg:.1f}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# NVIDIA Script
# ---------------------------------------------------------------------------

def _nvidia_script(hw: HardwareProfile, gpu: DetectedGPU,
                   model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, {gpu.vram_mb}MB VRAM)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-gpu numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"
CACHE_DIR = "./trt_engine_cache"


def main():
    import onnxruntime as ort

    print()
    print("=" * 60)
    print("  ISAT Inference — NVIDIA GPU")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  GPU  : {gpu.name} ({gpu.arch}, {gpu.vram_mb}MB)")
    print("=" * 60)
    print()

    os.makedirs(CACHE_DIR, exist_ok=True)

    sess_opts = ort.SessionOptions()

    providers = [
        ("TensorrtExecutionProvider", {{
            "trt_fp16_enable": True,
            "trt_engine_cache_enable": True,
            "trt_engine_cache_path": CACHE_DIR,
        }}),
        ("CUDAExecutionProvider", {{"device_id": 0}}),
        "CPUExecutionProvider",
    ]

    print("Loading model (TensorRT will compile an optimized engine)...")
    print("(First run builds the engine and caches it — subsequent runs are fast)")
    print()
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    print(f"Ready in {{time.perf_counter() - t0:.1f}}s")
    print(f"Active EP: {{session.get_providers()[0]}}")
    print()

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))

    output_names = [o.name for o in session.get_outputs()]

    for i in range(3):
        session.run(output_names, inputs)
    print("Warmup done. Benchmarking...")

    latencies = []
    for i in range(10):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        ms = (time.perf_counter() - t0) * 1000
        latencies.append(ms)
        print(f"  Run {{i+1:>2}}: {{ms:.2f}} ms")

    avg = sum(latencies) / len(latencies)
    print(f"\\nMean: {{avg:.2f}} ms | FPS: {{1000/avg:.1f}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Intel Script
# ---------------------------------------------------------------------------

def _intel_script(hw: HardwareProfile, gpu: DetectedGPU,
                  model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    is_igpu = gpu.gpu_type in ("igpu", "integrated")

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} (Intel {"iGPU" if is_igpu else "dGPU"}, {gpu.arch})

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-openvino numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

os.environ["OMP_NUM_THREADS"] = "{hw.cpu_cores}"

MODEL_PATH = r"{model_path}"


def main():
    import onnxruntime as ort

    print()
    print("=" * 60)
    print("  ISAT Inference — Intel {'iGPU' if is_igpu else 'dGPU'}")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Device: {gpu.name}")
    print("=" * 60)
    print()

    sess_opts = ort.SessionOptions()

    providers = [
        ("OpenVINOExecutionProvider", {{
            "device_type": "{'GPU.0' if is_igpu else 'GPU'}",
            "precision": "FP16",
        }}),
        "CPUExecutionProvider",
    ]

    print("Loading model with OpenVINO EP...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    print(f"Ready in {{time.perf_counter() - t0:.1f}}s")
    print(f"Active EP: {{session.get_providers()[0]}}")
    print()

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))

    output_names = [o.name for o in session.get_outputs()]

    for i in range(3):
        session.run(output_names, inputs)
    print("Warmup done. Benchmarking...")

    latencies = []
    for i in range(10):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        ms = (time.perf_counter() - t0) * 1000
        latencies.append(ms)
        print(f"  Run {{i+1:>2}}: {{ms:.2f}} ms")

    avg = sum(latencies) / len(latencies)
    print(f"\\nMean: {{avg:.2f}} ms | FPS: {{1000/avg:.1f}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Apple Script
# ---------------------------------------------------------------------------

def _apple_script(hw: HardwareProfile, gpu: DetectedGPU,
                  model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} (Apple Silicon, {hw.system_ram_mb // 1024}GB Unified Memory)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime numpy
"""

import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"


def main():
    import onnxruntime as ort

    print()
    print("=" * 60)
    print("  ISAT Inference — Apple Silicon")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Chip : {gpu.name}")
    print("=" * 60)
    print()

    sess_opts = ort.SessionOptions()

    providers = [
        ("CoreMLExecutionProvider", {{}}),
        "CPUExecutionProvider",
    ]

    print("Loading model with CoreML EP (GPU + Neural Engine)...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    print(f"Ready in {{time.perf_counter() - t0:.1f}}s")
    print(f"Active EP: {{session.get_providers()[0]}}")
    print()

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))

    output_names = [o.name for o in session.get_outputs()]

    for i in range(3):
        session.run(output_names, inputs)
    print("Warmup done. Benchmarking...")

    latencies = []
    for i in range(10):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        ms = (time.perf_counter() - t0) * 1000
        latencies.append(ms)
        print(f"  Run {{i+1:>2}}: {{ms:.2f}} ms")

    avg = sum(latencies) / len(latencies)
    print(f"\\nMean: {{avg:.2f}} ms | FPS: {{1000/avg:.1f}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Qualcomm Script
# ---------------------------------------------------------------------------

def _qualcomm_script(hw: HardwareProfile, gpu: DetectedGPU,
                     model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, Hexagon NPU)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-qnn numpy
"""

import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"


def main():
    import onnxruntime as ort

    print()
    print("=" * 60)
    print("  ISAT Inference — Qualcomm NPU")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print("=" * 60)
    print()

    sess_opts = ort.SessionOptions()

    providers = [
        ("QNNExecutionProvider", {{
            "backend_path": "libQnnHtp.so",
        }}),
        "CPUExecutionProvider",
    ]

    print("Loading model with QNN EP (Hexagon HTP)...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    print(f"Ready in {{time.perf_counter() - t0:.1f}}s")
    print(f"Active EP: {{session.get_providers()[0]}}")
    print()

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))

    output_names = [o.name for o in session.get_outputs()]

    for i in range(3):
        session.run(output_names, inputs)
    print("Warmup done. Benchmarking...")

    latencies = []
    for i in range(10):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        ms = (time.perf_counter() - t0) * 1000
        latencies.append(ms)
        print(f"  Run {{i+1:>2}}: {{ms:.2f}} ms")

    avg = sum(latencies) / len(latencies)
    print(f"\\nMean: {{avg:.2f}} ms | FPS: {{1000/avg:.1f}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# CPU-only Script
# ---------------------------------------------------------------------------

def _cpu_script(hw: HardwareProfile, model_path: str,
                model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: CPU ({hw.cpu_name}, {hw.cpu_cores} cores)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

os.environ["OMP_NUM_THREADS"] = "{hw.cpu_cores}"

MODEL_PATH = r"{model_path}"


def main():
    import onnxruntime as ort

    print()
    print("=" * 60)
    print("  ISAT Inference — CPU")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  CPU  : {hw.cpu_name} ({{os.cpu_count()}} cores)")
    print("=" * 60)
    print()

    sess_opts = ort.SessionOptions()
    sess_opts.intra_op_num_threads = {hw.cpu_cores}
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

    print("Loading model on CPU...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=["CPUExecutionProvider"])
    print(f"Ready in {{time.perf_counter() - t0:.1f}}s")
    print()

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))

    output_names = [o.name for o in session.get_outputs()]

    for i in range(3):
        session.run(output_names, inputs)
    print("Warmup done. Benchmarking...")

    latencies = []
    for i in range(10):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        ms = (time.perf_counter() - t0) * 1000
        latencies.append(ms)
        print(f"  Run {{i+1:>2}}: {{ms:.2f}} ms")

    avg = sum(latencies) / len(latencies)
    print(f"\\nMean: {{avg:.2f}} ms | FPS: {{1000/avg:.1f}}")


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_script(hw: HardwareProfile, model_path: str) -> str:
    """Generate a complete, runnable inference script for the detected hardware."""
    model_mb = 0.0
    p = Path(model_path)
    if p.exists():
        model_mb = p.stat().st_size / (1024 * 1024)
        for ed in p.parent.glob("*.onnx.data"):
            model_mb += ed.stat().st_size / (1024 * 1024)

    fp_hash = _fingerprint(hw, model_path)
    gpu = hw.primary_gpu

    if not gpu:
        return _cpu_script(hw, model_path, model_mb, fp_hash)

    if gpu.vendor == "amd":
        if gpu.gpu_type == "apu":
            return _amd_apu_script(hw, gpu, model_path, model_mb, fp_hash)
        return _amd_dgpu_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "nvidia":
        return _nvidia_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "intel":
        return _intel_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "apple":
        return _apple_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "qualcomm":
        return _qualcomm_script(hw, gpu, model_path, model_mb, fp_hash)
    else:
        return _cpu_script(hw, model_path, model_mb, fp_hash)


def save_script(hw: HardwareProfile, model_path: str,
                output_dir: str = "isat_output") -> str:
    """Generate and save the script to a file. Returns the file path."""
    script = generate_script(hw, model_path)
    model_name = _model_basename(model_path)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{model_name}_inference.py"
    out_path.write_text(script)
    out_path.chmod(0o755)
    return str(out_path)
