"""Generate complete, runnable inference scripts for any hardware + model.

Each generated script is:
  - Self-contained (no external dependencies beyond ORT + numpy)
  - Correctly configured for the detected hardware
  - Has environment variable setup baked in
  - Has swap / kernel param checks
  - Has a professional header with copyright and hardware fingerprint
  - Actually runs end-to-end (tested on real hardware)
"""

from __future__ import annotations

import hashlib
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from isat import __version__
from isat.auto_detect.detector import DetectedGPU, HardwareProfile


def _fingerprint(hw: HardwareProfile, model_path: str) -> str:
    """Generate a unique hash for this hardware + model combination."""
    gpu = hw.primary_gpu
    identity = (
        f"{hw.cpu_name}:{hw.system_ram_mb}:"
        f"{gpu.vendor if gpu else 'cpu'}:{gpu.arch if gpu else ''}:"
        f"{gpu.vram_mb if gpu else 0}:{gpu.shared_mem_mb if gpu else 0}:"
        f"{model_path}"
    )
    return hashlib.sha256(identity.encode()).hexdigest()[:12]


def _model_basename(model_path: str) -> str:
    p = Path(model_path)
    stem = p.stem.replace("-", "_").replace(".", "_")
    # Generic names like model, model_safe, model_fixed cause collisions —
    # prefix with parent directory name to disambiguate
    if stem in ("model", "model_safe", "model_fixed", "encoder_model",
                "decoder_model", "flow", "action"):
        parent = p.parent.name.replace("-", "_").replace(".", "_")
        if parent and parent != ".":
            stem = f"{parent}_{stem}"
    return stem


# ---------------------------------------------------------------------------
# AMD APU Script
# ---------------------------------------------------------------------------

def _amd_apu_script(hw: HardwareProfile, gpu: DetectedGPU,
                    model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    runtime_gb = model_mb * 2.5 / 1024
    need_swap_warning = runtime_gb > 8
    swap_recommended = max(int(runtime_gb * 4), 16)

    env_block = """\
os.environ["HSA_XNACK"] = "1"
os.environ.setdefault("HSA_ENABLE_DXG_DETECTION", "1")
os.environ.setdefault("HSA_OVERRIDE_GFX_VERSION", "11.0.0")
os.environ["MIGRAPHX_GPU_COMPILE_PARALLEL"] = "1"
os.environ.setdefault("MIGRAPHX_GPU_HIP_FLAGS",
                       "-ftemplate-depth=2048 -Wno-error=stack-exhausted -Wno-stack-exhausted")
"""

    swap_check = ""
    if need_swap_warning:
        swap_check = f"""
    swap_gb = _get_swap_gb()
    if swap_gb < {swap_recommended}:
        print(f"  [WARNING] Swap is only {{swap_gb:.0f}} GB. Recommended: >= {swap_recommended} GB")
        print(f"  MIGraphX compilation of large models uses heavy swap.")
        print(f"  To add swap:")
        print(f"    sudo fallocate -l {swap_recommended}G /swapfile_isat")
        print(f"    sudo chmod 600 /swapfile_isat")
        print(f"    sudo mkswap /swapfile_isat && sudo swapon /swapfile_isat")
    else:
        print(f"  [OK] Swap: {{swap_gb:.0f}} GB (>= {swap_recommended} GB)")
"""

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, {gpu.gpu_type.upper()})

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  This script is ready to run. It will:
    1. Verify system requirements (GPU, drivers, memory, swap)
    2. Set the correct environment variables for {gpu.arch}
    3. Load and compile the model with MIGraphX EP (FP16)
    4. Run a test inference and print timing
    5. Verify the correct execution provider is active

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-migraphx numpy
"""

import os
import resource
import subprocess
import sys
import time
from pathlib import Path

# ============================================================================
#  ENVIRONMENT CONFIGURATION
#  These MUST be set BEFORE importing onnxruntime.
#  Optimized for AMD APU inference with MIGraphX EP.
# ============================================================================

{env_block}
# Increase process stack size so comgr (in-process LLVM) survives
# deep template recursion during MIGraphX kernel compilation.
try:
    resource.setrlimit(resource.RLIMIT_STACK,
                       (resource.RLIM_INFINITY, resource.RLIM_INFINITY))
except Exception:
    pass

# Lift the system-memory limit on GTT allocations so hipHostMalloc
# can allocate beyond physical RAM using swap-backed pages.
try:
    _nsml = open("/sys/module/amdgpu/parameters/no_system_mem_limit").read().strip()
    if _nsml != "Y":
        subprocess.run(["sudo", "-S", "sh", "-c",
                        "echo Y > /sys/module/amdgpu/parameters/no_system_mem_limit"],
                       input="\\n", text=True, capture_output=True, timeout=5)
except Exception:
    pass

# ============================================================================
#  SYSTEM CHECKS
# ============================================================================

def _get_swap_gb() -> float:
    try:
        for line in Path("/proc/meminfo").read_text().splitlines():
            if line.startswith("SwapTotal:"):
                return int(line.split()[1]) / (1024 * 1024)
    except OSError:
        pass
    return 0.0


def _get_vram_mb() -> int:
    for card in sorted(Path("/sys/class/drm").glob("card*/device")):
        vt = card / "mem_info_vram_total"
        if vt.exists():
            try:
                return int(vt.read_text().strip()) // (1024 * 1024)
            except (OSError, ValueError):
                pass
    return 0


def _get_gtt_mb() -> int:
    for card in sorted(Path("/sys/class/drm").glob("card*/device")):
        gt = card / "mem_info_gtt_total"
        if gt.exists():
            try:
                return int(gt.read_text().strip()) // (1024 * 1024)
            except (OSError, ValueError):
                pass
    return 0


def preflight_checks():
    """Verify this system meets all requirements before running."""
    print()
    print("=" * 60)
    print("  ISAT Pre-flight System Check")
    print("=" * 60)
    print()

    ok = True

    # Check HSA_XNACK
    xnack = os.environ.get("HSA_XNACK", "0")
    if xnack == "1":
        print("  [OK] HSA_XNACK=1 (unified memory enabled)")
    else:
        print("  [FAIL] HSA_XNACK not set! Large models will fail.")
        ok = False

    # Check GPU
    vram = _get_vram_mb()
    gtt = _get_gtt_mb()
    if vram > 0 or gtt > 0:
        print(f"  [OK] GPU detected: VRAM={{vram}}MB, GTT={{gtt}}MB")
        if vram < 2048 and gtt > 4096:
            print(f"  [OK] APU mode: unified memory via GTT")
    else:
        print("  [FAIL] No AMD GPU detected in sysfs")
        ok = False
{swap_check}
    # Check no_system_mem_limit
    try:
        nsml = open("/sys/module/amdgpu/parameters/no_system_mem_limit").read().strip()
        if nsml == "Y":
            print("  [OK] no_system_mem_limit=Y (GTT can use swap)")
        else:
            print(f"  [WARNING] no_system_mem_limit={{nsml}} — large models may OOM")
            print(f"  Fix: sudo sh -c 'echo Y > /sys/module/amdgpu/parameters/no_system_mem_limit'")
    except Exception:
        pass

    # Check model external data files
    model_dir = Path(MODEL_PATH).parent
    data_files = list(model_dir.glob("*.onnx_data")) + list(model_dir.glob("*.data"))
    if data_files:
        total_data = sum(f.stat().st_size for f in data_files) / (1024 * 1024)
        print(f"  [OK] External data files: {{len(data_files)}} ({{total_data:.0f}} MB)")

    # Check ORT
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "MIGraphXExecutionProvider" in providers:
            print("  [OK] MIGraphX EP available")
        else:
            print("  [WARNING] MIGraphX EP not found — will fall back to CPU")
            print("  Install: pip install onnxruntime-migraphx")
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        print("  Install: pip install onnxruntime-migraphx")
        ok = False

    # Check model file
    model = Path(MODEL_PATH)
    if model.exists():
        size_mb = model.stat().st_size / (1024 * 1024)
        print(f"  [OK] Model found: {{size_mb:.1f}} MB")
    else:
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False

    print()
    if ok:
        print("  All checks passed. Ready to run.")
    else:
        print("  Some checks failed. Fix the issues above before running.")
    print("=" * 60)
    print()
    return ok


# ============================================================================
#  MODEL CONFIGURATION
# ============================================================================

MODEL_PATH = r"{model_path}"


# ============================================================================
#  INFERENCE
# ============================================================================

def create_session():
    """Create an ORT inference session with MIGraphX EP."""
    import onnxruntime as ort

    sess_opts = ort.SessionOptions()
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    sess_opts.log_severity_level = 3

    providers = [
        ("MIGraphXExecutionProvider", {{
            "migraphx_fp16_enable": "1",
            "device_id": "0",
        }}),
        "CPUExecutionProvider",
    ]

    print("Loading model and compiling with MIGraphX...")
    print("(First run compiles the model — this can take minutes for large models)")
    print()

    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    compile_time = time.perf_counter() - t0

    # CRITICAL: Verify MIGraphX is actually active
    active_ep = session.get_providers()[0]
    if "MIGraphX" not in active_ep:
        print(f"  [WARNING] Expected MIGraphX but got: {{active_ep}}")
        print(f"  ORT silently fell back to CPU. Check your ORT build.")
    else:
        print(f"  [OK] Running on: {{active_ep}}")

    print(f"  Compile time: {{compile_time:.1f}}s")
    print()
    return session


def _build_inputs(session, use_zeros=False):
    """Build test inputs. Use zeros for models with index-based ops (GatherND, ScatterND)."""
    import numpy as np
    _DIM_DEFAULTS = {{
        "batch_size": 1, "batch": 1,
        "num_channels": 3, "channels": 3, "channel": 3,
        "height": 224, "width": 224,
        "sequence_length": 16, "seq_len": 16, "seq_length": 16, "length": 16,
        "num_heads": 12, "head_dim": 64,
        "image_batch_size": 1, "text_batch_size": 1,
        "past_sequence_length": 0,
    }}
    inputs = {{}}
    for inp in session.get_inputs():
        shape = []
        for dim in inp.shape:
            if isinstance(dim, int) and dim > 0:
                shape.append(dim)
            elif isinstance(dim, str) and dim in _DIM_DEFAULTS:
                shape.append(_DIM_DEFAULTS[dim])
            elif isinstance(dim, str) and "+" in dim:
                parts = [p.strip() for p in dim.split("+")]
                total = sum(_DIM_DEFAULTS.get(p, 1) for p in parts)
                shape.append(max(total, 1))
            else:
                shape.append(1)
        dtype_map = {{
            "tensor(float)": np.float32,
            "tensor(float16)": np.float16,
            "tensor(int64)": np.int64,
            "tensor(int32)": np.int32,
            "tensor(bool)": np.bool_,
            "tensor(uint8)": np.uint8,
            "tensor(double)": np.float64,
        }}
        np_dtype = dtype_map.get(inp.type, np.float32)
        if use_zeros:
            inputs[inp.name] = np.zeros(shape, dtype=np_dtype)
        else:
            inputs[inp.name] = np.random.randn(*shape).astype(np_dtype)
    return inputs


def run_inference(session, warmup: int = 3, measured: int = 10):
    """Run warmup + measured inference and print timing stats."""
    import numpy as np

    inputs = _build_inputs(session, use_zeros=False)
    output_names = [o.name for o in session.get_outputs()]

    # Try random data first; if it fails (GatherND/ScatterND index OOB), retry with zeros
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (likely index-based ops) — retrying with zeros")
        inputs = _build_inputs(session, use_zeros=True)

    # Warmup
    print(f"Warmup ({{warmup}} iterations)...")
    for i in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()

    # Measured
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")

    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    mn = min(latencies)
    mx = max(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    fps = 1000.0 / avg if avg > 0 else 0

    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{mn:>10.2f}} ms")
    print(f"  Max    : {{mx:>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{fps:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : MIGraphXExecutionProvider (FP16)")
    print(f"  Target : {gpu.name} ({gpu.arch})")
    print("=" * 60)
    print()


# ============================================================================
#  MAIN
# ============================================================================

if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} ({gpu.arch})")
    print("=" * 60)

    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)

    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# AMD dGPU Script
# ---------------------------------------------------------------------------

def _amd_dgpu_script(hw: HardwareProfile, gpu: DetectedGPU,
                     model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    vram_warn = f"""
    if model_mb > {gpu.vram_mb}:
        print(f"  [WARNING] Model ({{model_mb:.0f}} MB) > VRAM ({gpu.vram_mb} MB) — may spill to system RAM")
        ok = False""" if gpu.vram_mb > 0 else ""

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, dGPU, {gpu.vram_mb}MB VRAM)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-migraphx numpy
"""

import os
import resource
import sys
import time
from pathlib import Path

import numpy as np

# dGPU uses dedicated VRAM — XNACK off (no unified memory needed)
os.environ["HSA_XNACK"] = "0"
os.environ.setdefault("MIGRAPHX_GPU_COMPILE_PARALLEL", "1")
os.environ.setdefault("MIGRAPHX_GPU_HIP_FLAGS",
                       "-ftemplate-depth=2048 -Wno-error=stack-exhausted -Wno-stack-exhausted")

try:
    resource.setrlimit(resource.RLIMIT_STACK,
                       (resource.RLIM_INFINITY, resource.RLIM_INFINITY))
except Exception:
    pass

MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (AMD dGPU)")
    print("=" * 60)
    print()
    ok = True
    model_mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024) if Path(MODEL_PATH).exists() else 0
{vram_warn}
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "MIGraphXExecutionProvider" in providers:
            print("  [OK] MIGraphX EP available")
        else:
            print("  [WARNING] MIGraphX EP not found — will fall back to CPU")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        print(f"  [OK] Model found: {{model_mb:.1f}} MB")
    print()
    if ok:
        print("  All checks passed.")
    print("=" * 60)
    print()
    return ok


def create_session():
    import onnxruntime as ort
    sess_opts = ort.SessionOptions()
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    sess_opts.log_severity_level = 3
    providers = [
        ("MIGraphXExecutionProvider", {{
            "migraphx_fp16_enable": "1",
            "device_id": "0",
        }}),
        "CPUExecutionProvider",
    ]
    print("Loading and compiling model with MIGraphX EP...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    active_ep = session.get_providers()[0]
    print(f"  [OK] Running on: {{active_ep}}")
    print(f"  Compile time: {{time.perf_counter() - t0:.1f}}s")
    assert "MIGraphX" in active_ep, f"Expected MIGraphX EP but got {{active_ep}} — silent CPU fallback!"
    print()
    return session


def run_inference(session, warmup=3, measured=10):
    import numpy as np
    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : MIGraphXExecutionProvider (FP16)")
    print(f"  Target : {gpu.name} ({gpu.arch}, {gpu.vram_mb}MB VRAM)")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} ({gpu.arch})")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# NVIDIA Script
# ---------------------------------------------------------------------------

def _nvidia_script(hw: HardwareProfile, gpu: DetectedGPU,
                   model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, {gpu.vram_mb}MB VRAM)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-gpu numpy
"""

import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"
CACHE_DIR = "./trt_engine_cache"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (NVIDIA)")
    print("=" * 60)
    print()
    ok = True
    try:
        r = subprocess.run(["nvidia-smi", "--query-gpu=name,memory.total",
                            "--format=csv,noheader"], capture_output=True, text=True, timeout=10)
        if r.returncode == 0:
            print(f"  [OK] GPU: {{r.stdout.strip()}}")
        else:
            print("  [WARNING] nvidia-smi failed")
    except FileNotFoundError:
        print("  [WARNING] nvidia-smi not found — NVIDIA driver may not be installed")
        ok = False
    model_mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024) if Path(MODEL_PATH).exists() else 0
    if model_mb > {gpu.vram_mb} and {gpu.vram_mb} > 0:
        print(f"  [WARNING] Model ({{model_mb:.0f}} MB) > VRAM ({gpu.vram_mb} MB)")
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "TensorrtExecutionProvider" in providers:
            print("  [OK] TensorRT EP available")
        elif "CUDAExecutionProvider" in providers:
            print("  [OK] CUDA EP available (TensorRT not found — using CUDA)")
        else:
            print("  [WARNING] No NVIDIA EP found — will fall back to CPU")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        print(f"  [OK] Model found: {{model_mb:.1f}} MB")
    print()
    if ok:
        print("  All checks passed.")
    print("=" * 60)
    print()
    return ok


def create_session():
    import onnxruntime as ort
    os.makedirs(CACHE_DIR, exist_ok=True)
    sess_opts = ort.SessionOptions()
    sess_opts.log_severity_level = 3
    providers = [
        ("TensorrtExecutionProvider", {{
            "trt_fp16_enable": True,
            "trt_engine_cache_enable": True,
            "trt_engine_cache_path": CACHE_DIR,
        }}),
        ("CUDAExecutionProvider", {{"device_id": 0}}),
        "CPUExecutionProvider",
    ]
    print("Loading model (TensorRT will compile an optimized engine)...")
    print("(First run builds the engine and caches it — subsequent runs are fast)")
    print()
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    active_ep = session.get_providers()[0]
    print(f"  [OK] Running on: {{active_ep}}")
    print(f"  Load time: {{time.perf_counter() - t0:.1f}}s")
    if active_ep == "CPUExecutionProvider":
        print("  [WARNING] Fell back to CPU! Check CUDA/TensorRT installation.")
    print()
    return session


def run_inference(session, warmup=3, measured=10):
    import numpy as np
    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : {{session.get_providers()[0]}}")
    print(f"  Target : {gpu.name} ({gpu.arch}, {gpu.vram_mb}MB)")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} ({gpu.arch})")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# Intel Script
# ---------------------------------------------------------------------------

def _intel_script(hw: HardwareProfile, gpu: DetectedGPU,
                  model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    is_igpu = gpu.gpu_type in ("igpu", "integrated")
    gpu_label = "iGPU" if is_igpu else "dGPU"
    device_type = "GPU.0" if is_igpu else "GPU"

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} (Intel {gpu_label}, {gpu.arch})

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-openvino numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

os.environ["OMP_NUM_THREADS"] = "{hw.cpu_cores}"

MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (Intel {gpu_label})")
    print("=" * 60)
    print()
    ok = True
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "OpenVINOExecutionProvider" in providers:
            print("  [OK] OpenVINO EP available")
        else:
            print("  [WARNING] OpenVINO EP not found — will fall back to CPU")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024)
        print(f"  [OK] Model found: {{mb:.1f}} MB")
    print()
    if ok:
        print("  All checks passed.")
    print("=" * 60)
    print()
    return ok


def create_session():
    import onnxruntime as ort
    sess_opts = ort.SessionOptions()
    sess_opts.log_severity_level = 3
    providers = [
        ("OpenVINOExecutionProvider", {{
            "device_type": "{device_type}",
            "precision": "FP16",
        }}),
        "CPUExecutionProvider",
    ]
    print("Loading model with OpenVINO EP...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    active_ep = session.get_providers()[0]
    print(f"  [OK] Running on: {{active_ep}}")
    print(f"  Load time: {{time.perf_counter() - t0:.1f}}s")
    if active_ep == "CPUExecutionProvider":
        print("  [WARNING] Fell back to CPU! Check OpenVINO installation.")
    print()
    return session


def run_inference(session, warmup=3, measured=10):
    import numpy as np
    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : {{session.get_providers()[0]}}")
    print(f"  Target : {gpu.name} (Intel {gpu_label})")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} (Intel {gpu_label})")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# Apple Script
# ---------------------------------------------------------------------------

def _apple_script(hw: HardwareProfile, gpu: DetectedGPU,
                  model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    ram_gb = hw.system_ram_mb // 1024

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} (Apple Silicon, {ram_gb}GB Unified Memory)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime numpy
"""

import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (Apple Silicon)")
    print("=" * 60)
    print()
    ok = True
    import platform
    if platform.machine() in ("arm64", "aarch64"):
        print(f"  [OK] Apple Silicon detected ({{platform.machine()}})")
    else:
        print(f"  [WARNING] Not Apple Silicon ({{platform.machine()}})")
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "CoreMLExecutionProvider" in providers:
            print("  [OK] CoreML EP available (GPU + Neural Engine)")
        else:
            print("  [WARNING] CoreML EP not found — will fall back to CPU")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024)
        print(f"  [OK] Model found: {{mb:.1f}} MB")
    print()
    if ok:
        print("  All checks passed.")
    print("=" * 60)
    print()
    return ok


def create_session():
    import onnxruntime as ort
    sess_opts = ort.SessionOptions()
    sess_opts.log_severity_level = 3
    providers = [
        ("CoreMLExecutionProvider", {{}}),
        "CPUExecutionProvider",
    ]
    print("Loading model with CoreML EP (GPU + Neural Engine)...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    active_ep = session.get_providers()[0]
    print(f"  [OK] Running on: {{active_ep}}")
    print(f"  Load time: {{time.perf_counter() - t0:.1f}}s")
    if active_ep == "CPUExecutionProvider":
        print("  [WARNING] Fell back to CPU! Check CoreML availability.")
    print()
    return session


def run_inference(session, warmup=3, measured=10):
    import numpy as np
    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : {{session.get_providers()[0]}}")
    print(f"  Target : {gpu.name} ({ram_gb}GB Unified Memory)")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} (Apple Silicon)")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# Qualcomm Script
# ---------------------------------------------------------------------------

def _qualcomm_script(hw: HardwareProfile, gpu: DetectedGPU,
                     model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} ({gpu.arch}, Hexagon NPU)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime-qnn numpy
"""

import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (Qualcomm NPU)")
    print("=" * 60)
    print()
    ok = True
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "QNNExecutionProvider" in providers:
            print("  [OK] QNN EP available (Hexagon HTP)")
        else:
            print("  [WARNING] QNN EP not found — will fall back to CPU")
            print("  Ensure Qualcomm QNN SDK is installed and libQnnHtp.so is accessible")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024)
        print(f"  [OK] Model found: {{mb:.1f}} MB")
    print()
    if ok:
        print("  All checks passed.")
    print("=" * 60)
    print()
    return ok


def create_session():
    import onnxruntime as ort
    sess_opts = ort.SessionOptions()
    sess_opts.log_severity_level = 3
    providers = [
        ("QNNExecutionProvider", {{
            "backend_path": "libQnnHtp.so",
        }}),
        "CPUExecutionProvider",
    ]
    print("Loading model with QNN EP (Hexagon HTP)...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    active_ep = session.get_providers()[0]
    print(f"  [OK] Running on: {{active_ep}}")
    print(f"  Load time: {{time.perf_counter() - t0:.1f}}s")
    if active_ep == "CPUExecutionProvider":
        print("  [WARNING] Fell back to CPU! Check QNN SDK installation.")
    print()
    return session


def run_inference(session, warmup=3, measured=10):
    import numpy as np
    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : {{session.get_providers()[0]}}")
    print(f"  Target : {gpu.name} (Hexagon NPU)")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} (Qualcomm NPU)")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# Windows MIGraphX EP via WinML CompileApi (AMD GPU only)
# ---------------------------------------------------------------------------

def _winml_migraphx_script(hw: HardwareProfile, gpu: DetectedGPU,
                            model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    ep_dir = hw.winml_ep_path
    vram_label = f"{gpu.vram_mb}MB VRAM" if gpu.vram_mb else "shared memory"

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} (MIGraphX EP via WinML CompileApi)
  OS    : Windows (ORT CompileApi → WinML → MIGraphX EP → AMD GPU)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Execution Path:
    Python → ORT CompileApi → WinML → MIGraphX EP → AMD GPU ({gpu.name})

  Key Insight:
    Do NOT use providers= in InferenceSession() — use the CompileApi path:
    ort.register_execution_provider_library() + so.add_provider_for_devices()

  Usage:
    python {model_name}_inference.py

  Requirements:
    pip install onnxruntime numpy
    WinML AMD EP AppX package (MicrosoftCorporationII.WinML.AMD.GPU.EP)
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

# ============================================================================
#  WinML MIGraphX EP Registration (CompileApi)
# ============================================================================

EP_DIR = r"{ep_dir}"
MIGRAPHX_DLL = os.path.join(EP_DIR, "onnxruntime_providers_migraphx.dll")
MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (Windows MIGraphX CompileApi)")
    print("=" * 60)
    print()
    ok = True

    # EP package check
    if os.path.isfile(MIGRAPHX_DLL):
        print(f"  [OK] WinML AMD EP found: {{os.path.basename(EP_DIR)}}")
    else:
        print(f"  [FAIL] MIGraphX DLL not found: {{MIGRAPHX_DLL}}")
        print(f"         Install WinML AMD EP AppX from Microsoft Store")
        ok = False

    # ORT check
    try:
        import onnxruntime as ort
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(ort.get_available_providers())}}")
        if hasattr(ort, 'register_execution_provider_library'):
            print("  [OK] CompileApi supported (register_execution_provider_library)")
        else:
            print("  [FAIL] ORT too old — needs 1.23+ for CompileApi")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False

    # Model check
    model_mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024) if Path(MODEL_PATH).exists() else 0
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        print(f"  [OK] Model found: {{model_mb:.1f}} MB")

    print()
    if ok:
        print("  All checks passed. Ready to run.")
    else:
        print("  Some checks failed. Fix the issues above before running.")
    print("=" * 60)
    print()
    return ok


def create_session():
    """Create ORT session with MIGraphX EP via WinML CompileApi."""
    import onnxruntime as ort

    # Step 1: Add DLL directory
    os.add_dll_directory(EP_DIR)

    # Step 2: Register MIGraphX provider library
    ort.register_execution_provider_library(
        "MIGraphXExecutionProvider", MIGRAPHX_DLL
    )

    # Step 3: Get EP devices
    devices = ort.get_ep_devices()
    migraphx_dev = [d for d in devices if d.ep_name == "MIGraphXExecutionProvider"]
    cpu_dev = [d for d in devices if d.ep_name == "CPUExecutionProvider"]

    if not migraphx_dev:
        print("  [WARNING] No MIGraphX device found — falling back to CPU")

    # Step 4: Add providers via CompileApi (NOT providers= in InferenceSession)
    so = ort.SessionOptions()
    so.log_severity_level = 3
    if migraphx_dev:
        so.add_provider_for_devices(migraphx_dev, {{}})
    so.add_provider_for_devices(cpu_dev, {{}})

    print("Loading model with MIGraphX EP via WinML CompileApi...")
    print("(First run compiles the MIGraphX graph — this can take 30-60+ seconds)")
    print()

    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, so)
    compile_time = time.perf_counter() - t0

    active_ep = session.get_providers()[0]
    if "MIGraphX" not in active_ep:
        print(f"  [WARNING] Expected MIGraphX but got: {{active_ep}}")
    else:
        print(f"  [OK] Running on: {{active_ep}}")

    print(f"  Compile time: {{compile_time:.1f}}s")
    print()
    return session


def run_inference(session, warmup: int = 3, measured: int = 10):
    """Run warmup + measured inference and print timing stats."""
    import numpy as np

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : MIGraphXExecutionProvider (WinML CompileApi)")
    print(f"  Target : {gpu.name} ({vram_label})")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} (MIGraphX via WinML)")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# Windows DirectML Script (works for ANY GPU: AMD, NVIDIA, Intel, Qualcomm)
# ---------------------------------------------------------------------------

def _directml_script(hw: HardwareProfile, gpu: DetectedGPU,
                     model_path: str, model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)
    vram_label = f"{gpu.vram_mb}MB VRAM" if gpu.vram_mb else "shared memory"

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: {gpu.name} (DirectML, {vram_label})
  OS    : Windows (WinML → DirectX 12 → GPU)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Execution Path:
    WinML → ONNX Runtime → DirectML EP → DirectX 12 → {gpu.name}

  Usage:
    python {model_name}_inference.py

  Requirements:
    pip install onnxruntime-directml numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (Windows DirectML)")
    print("=" * 60)
    print()
    ok = True

    # GPU check via ORT
    try:
        import onnxruntime as ort
        providers = ort.get_available_providers()
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(providers)}}")
        if "DmlExecutionProvider" in providers:
            print("  [OK] DirectML EP available")
        else:
            print("  [FAIL] DmlExecutionProvider not found")
            print("         Install: pip install onnxruntime-directml")
            ok = False
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        print("         Install: pip install onnxruntime-directml")
        ok = False

    # Model check
    model_mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024) if Path(MODEL_PATH).exists() else 0
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        print(f"  [OK] Model found: {{model_mb:.1f}} MB")

    print()
    if ok:
        print("  All checks passed. Ready to run.")
    else:
        print("  Some checks failed. Fix the issues above before running.")
    print("=" * 60)
    print()
    return ok


def create_session():
    """Create an ORT inference session with DirectML EP."""
    import onnxruntime as ort

    sess_opts = ort.SessionOptions()
    sess_opts.log_severity_level = 3

    providers = [
        "DmlExecutionProvider",
        "CPUExecutionProvider",
    ]

    print("Loading model with DirectML EP...")
    print("(WinML → DirectX 12 → GPU)")
    print()

    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=providers)
    load_time = time.perf_counter() - t0

    active_ep = session.get_providers()[0]
    if "Dml" not in active_ep:
        print(f"  [WARNING] Expected DmlExecutionProvider but got: {{active_ep}}")
        print(f"  ORT silently fell back to CPU. Install onnxruntime-directml.")
    else:
        print(f"  [OK] Running on: {{active_ep}}")

    print(f"  Load time: {{load_time:.1f}}s")
    print()
    return session


def run_inference(session, warmup: int = 3, measured: int = 10):
    """Run warmup + measured inference and print timing stats."""
    import numpy as np

    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : DmlExecutionProvider (DirectML)")
    print(f"  Target : {gpu.name} ({vram_label})")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: {gpu.name} (DirectML)")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# CPU-only Script
# ---------------------------------------------------------------------------

def _cpu_script(hw: HardwareProfile, model_path: str,
                model_mb: float, fp_hash: str) -> str:
    model_name = _model_basename(model_path)

    return f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{'=' * 76}
  ISAT Auto-Generated Inference Script
  Model : {Path(model_path).name}
  Target: CPU ({hw.cpu_name}, {hw.cpu_cores} cores)

  Generated by ISAT (Inference Stack Auto-Tuner) v{__version__}
  https://github.com/SID-Devu/isat-tuner

  Copyright (c) 2026 Sudheer Ibrahim Daniel Devu. All rights reserved.
  Licensed under Apache 2.0 | https://pypi.org/project/isat-tuner/

  Hardware Fingerprint : {fp_hash}
  Generated At         : {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
  ISAT Version         : {__version__}
{'=' * 76}

  Usage:
    python3 {model_name}_inference.py

  Requirements:
    pip install onnxruntime numpy
"""

import os
import sys
import time
from pathlib import Path

import numpy as np

os.environ["OMP_NUM_THREADS"] = "{hw.cpu_cores}"

MODEL_PATH = r"{model_path}"


def preflight_checks() -> bool:
    print("=" * 60)
    print("  ISAT Pre-flight System Check (CPU)")
    print("=" * 60)
    print()
    ok = True
    try:
        import onnxruntime as ort
        print(f"  [OK] ORT {{ort.__version__}}: {{', '.join(ort.get_available_providers())}}")
    except ImportError:
        print("  [FAIL] onnxruntime not installed")
        ok = False
    if not Path(MODEL_PATH).exists():
        print(f"  [FAIL] Model not found: {{MODEL_PATH}}")
        ok = False
    else:
        mb = Path(MODEL_PATH).stat().st_size / (1024 * 1024)
        print(f"  [OK] Model found: {{mb:.1f}} MB")
    print(f"  [OK] CPU cores: {{os.cpu_count()}}, OMP_NUM_THREADS={hw.cpu_cores}")
    print()
    if ok:
        print("  All checks passed.")
    print("=" * 60)
    print()
    return ok


def create_session():
    import onnxruntime as ort
    sess_opts = ort.SessionOptions()
    sess_opts.intra_op_num_threads = {hw.cpu_cores}
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
    sess_opts.log_severity_level = 3
    print("Loading model on CPU (graph optimizations enabled)...")
    t0 = time.perf_counter()
    session = ort.InferenceSession(MODEL_PATH, sess_opts, providers=["CPUExecutionProvider"])
    print(f"  [OK] Ready in {{time.perf_counter() - t0:.1f}}s")
    print()
    return session


def run_inference(session, warmup=3, measured=10):
    import numpy as np
    inputs = {{}}
    for inp in session.get_inputs():
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp.shape]
        dtype_map = {{"tensor(float)": np.float32, "tensor(float16)": np.float16,
                     "tensor(int64)": np.int64, "tensor(int32)": np.int32}}
        inputs[inp.name] = np.random.randn(*shape).astype(dtype_map.get(inp.type, np.float32))
    output_names = [o.name for o in session.get_outputs()]
    try:
        session.run(output_names, inputs)
    except Exception:
        print("  [INFO] Random inputs failed (index-based ops) — retrying with zeros")
        for k in inputs:
            inputs[k] = np.zeros_like(inputs[k])
    print(f"Warmup ({{warmup}} iterations)...")
    for _ in range(warmup):
        session.run(output_names, inputs)
    print("Warmup complete.")
    print()
    print(f"Benchmarking ({{measured}} iterations)...")
    latencies = []
    for i in range(measured):
        t0 = time.perf_counter()
        session.run(output_names, inputs)
        elapsed = (time.perf_counter() - t0) * 1000
        latencies.append(elapsed)
        print(f"  Run {{i+1:>3}}: {{elapsed:>8.2f}} ms")
    print()
    print("=" * 60)
    print("  RESULTS")
    print("=" * 60)
    avg = sum(latencies) / len(latencies)
    p50 = sorted(latencies)[len(latencies) // 2]
    p95 = sorted(latencies)[int(len(latencies) * 0.95)]
    print(f"  Mean   : {{avg:>10.2f}} ms")
    print(f"  Min    : {{min(latencies):>10.2f}} ms")
    print(f"  Max    : {{max(latencies):>10.2f}} ms")
    print(f"  P50    : {{p50:>10.2f}} ms")
    print(f"  P95    : {{p95:>10.2f}} ms")
    print(f"  FPS    : {{1000.0/avg:>10.1f}}")
    print()
    print(f"  Model  : {{Path(MODEL_PATH).name}}")
    print(f"  EP     : CPUExecutionProvider")
    print(f"  Target : {hw.cpu_name} ({hw.cpu_cores} cores)")
    print("=" * 60)
    print()


if __name__ == "__main__":
    print()
    print("=" * 60)
    print("  ISAT Auto-Generated Inference Script")
    print(f"  Model: {{Path(MODEL_PATH).name}}")
    print(f"  Target: CPU ({hw.cpu_cores} cores)")
    print("=" * 60)
    if not preflight_checks():
        print("Fix the issues above and re-run.")
        sys.exit(1)
    session = create_session()
    run_inference(session, warmup=3, measured=10)
'''


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_script(hw: HardwareProfile, model_path: str) -> str:
    """Generate a complete, runnable inference script for the detected hardware."""
    model_mb = 0.0
    p = Path(model_path)
    if p.exists():
        model_mb = p.stat().st_size / (1024 * 1024)
        seen = {p.resolve()}
        for suffix in [".onnx_data", "_data"]:
            dp = p.parent / (p.stem + suffix)
            if dp.exists() and dp.resolve() not in seen:
                seen.add(dp.resolve())
                if dp.is_dir():
                    model_mb += sum(f.stat().st_size for f in dp.iterdir()) / (1024 * 1024)
                else:
                    model_mb += dp.stat().st_size / (1024 * 1024)
        for pat in ["*.onnx_data", "*.onnx.data", "*.data"]:
            for ed in p.parent.glob(pat):
                if ed.resolve() not in seen and ed.is_file():
                    seen.add(ed.resolve())
                    model_mb += ed.stat().st_size / (1024 * 1024)

    fp_hash = _fingerprint(hw, model_path)
    gpu = hw.primary_gpu

    if not gpu:
        return _cpu_script(hw, model_path, model_mb, fp_hash)

    is_windows = hw.os_name == "windows"

    # Windows: prefer MIGraphX via WinML CompileApi if AMD EP AppX is installed
    if is_windows and hw.winml_ep_path and gpu.vendor == "amd":
        return _winml_migraphx_script(hw, gpu, model_path, model_mb, fp_hash)
    if is_windows:
        return _directml_script(hw, gpu, model_path, model_mb, fp_hash)

    if gpu.vendor == "amd":
        if gpu.gpu_type == "apu":
            return _amd_apu_script(hw, gpu, model_path, model_mb, fp_hash)
        return _amd_dgpu_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "nvidia":
        return _nvidia_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "intel":
        return _intel_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "apple":
        return _apple_script(hw, gpu, model_path, model_mb, fp_hash)
    elif gpu.vendor == "qualcomm":
        return _qualcomm_script(hw, gpu, model_path, model_mb, fp_hash)
    else:
        return _cpu_script(hw, model_path, model_mb, fp_hash)


def save_script(hw: HardwareProfile, model_path: str,
                output_dir: str = "isat_output") -> str:
    """Generate and save the script to a file. Returns the file path."""
    script = generate_script(hw, model_path)
    model_name = _model_basename(model_path)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{model_name}_inference.py"
    out_path.write_text(script)
    out_path.chmod(0o755)
    return str(out_path)
